# Generated by Django 3.0.2 on 2020-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='contact',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
