# Generated by Django 3.0.2 on 2020-01-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20200123_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_added',
        ),
    ]
